version: '3'

volumes:
  sslcerts:
    driver: local

services:

  backend:
    # command: sleep infinity
    environment:
      ACTIVATE: 1
      APP_MODE: production
      DEBUG_LEVEL: INFO
      NGINX_ACTIVE: "True"
      B2ACCESS_ENV: development
      # EUDAT RELATED  # TODO: switch to production when B2ACCESS is ready
      # B2ACCESS_ENV: production
    depends_on:
      # - icat
      - postgres
    expose:
      - 8080
    volumes:
      - ../projects/eudat/builds/backend/fixip.sh:/docker-entrypoint.d/fixip.sh
      - ../data/b2handle:${HANDLE_CREDENTIALS_INTERNAL_PATH}

  proxy:
    environment:
      ACTIVATE: 1
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
    volumes:
      # SSL / HTTPS
      - ../confs/nginx/production.conf:/etc/nginx/sites-enabled/production
      - sslcerts:/etc/letsencrypt
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL

  # if using self signed certificates
  # and trying to test locally:
  restclient:
    environment:
      ACTIVATE: 0 # change for debugging
      APP_HOST: --verify /tmp/certs/real/fullchain1.pem https://${PROJECT_DOMAIN}
      APP_PORT:
      DOMAIN: ${PROJECT_DOMAIN}
      PROXY_HOST: ${PROXY_HOST}
    networks:
      proxy_net:
    depends_on:
      - proxy
    volumes:
      - sslcerts:/tmp/certs
