# ###############################################
# Copyright 2011-2017 EUDAT CDI - www.eudat.eu
# ###############################################

project:
  title: EUDAT-B2SAFE 'dockerized' server
  description: Processing files in different EUDAT domains
  version: 0.1.0

###############################
## Please CHECK VARIABLES here
## before starting your project
###############################
variables:

  env:

    IRODS_USER: irods
    IRODS_GUEST_USER: guest              # intended to work only with GSI
    IRODS_DEFAULT_ADMIN_USER: rodsminer  # intended to work only with GSI
    IRODS_ZONE: tempZone
    IRODS_HOME: home
    IRODS_AUTHSCHEME:   # to be auto-detected
    # IRODS_AUTHSCHEME: credentials
    # IRODS_AUTHSCHEME: GSI
    # NOTE: this must match ALCHEMY_PASSWORD
    IRODS_PASSWORD: chooseapasswordwisely
    IRODS_DB: ICAT
    IRODS_CHUNKSIZE: 1048576
    IRODS_ANONYMOUS: 1

    # Postgres configuration:
    ALCHEMY_USER: rods
    ALCHEMY_PASSWORD: chooseapasswordwisely
    ALCHEMY_DBS: ICAT
    ALCHEMY_API_DB:

    # B2access certificates path
    B2ACCESS_CAS: /tmp/certificates/b2access

controller:
  commands:
    irods_restart:
      description: Try to restart the current iCAT server instance
      command: service irods restart
      service: icat
      user: root

# Keep track of releases and dependencies
releases:
  '0.1.0':
    type: alpha
    rapydo: 0.6.1
    status: developing
