# ###############################################
# Copyright 2011-2017 EUDAT CDI - www.eudat.eu
# ###############################################

project:
  title: EUDAT proxy for all services
  description: a common interface in front of the EUDAT services
  version: 0.1.0

# environment configuration
variables:
  env:
    DOMAIN: eudat.eu

# Keep track of releases and dependencies
releases:
  '0.1.0':
    type: alpha
    rapydo: 0.6.1
    status: developing
