version: '3'

# #####################
# VOLUMES
# #####################

volumes:
  jwt_tokens:
    driver: local
  rabbitdata:
    driver: local
  sqldata:
    driver: local
  graphdata:
    driver: local
  mongodata:
    driver: local
  pureftpd:
    driver: local
  letsencrypt_certs:
    driver: local
  ssl_dhparam:
    driver: local

  # redisdata:
  #   driver: local

# #####################
# NETWORKS
# #####################

networks:
  # default:
  i_net:
  app_net:
  proxy_net:
  worker_net:
  ftp_net:
  db_net:
    # driver: bridge
    ipam:
      driver: default
      config:
        # Note: use this configuration to match inside internal rules
        # TOFIX: make this an env variable
        - subnet: ${DB_SUBNET}/16

# #####################
# SERVICES
# #####################
services:

  ########################
  ###  MAIN CONTAINER  ###
  ########################
  backend:
    # command: sleep infinity
    build: ../submodules/builds_base/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:template
    # hostname: restapi
    hostname: rapydo_server
    environment:
      ACTIVATE: 0  # activate me inside your Blueprint
      FLASK_APP: ${COMPOSE_PROJECT_NAME}/__main__.py
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
      # base the user/role mechanism on some database
      AUTH_ENABLE: 0
      # AUTH_SERVICE: ${AUTH_SERVICE}
    volumes:
      # Custom configuration
      - ../projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/${COMPOSE_PROJECT_NAME}/confs/project_configuration.yaml
      # Vanilla code
      - ../projects/${COMPOSE_PROJECT_NAME}/backend:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
      # Unit tests
      - ../submodules/backend/tests:/code/tests
      - ../projects/${COMPOSE_PROJECT_NAME}/backend/tests:/code/tests/custom
    networks:
      app_net:
        aliases:
          - ${FLASK_HOST}
      db_net:
      # i_net:

  ##############################
  proxy:
    build: ../submodules/builds_base/proxy
    image: ${COMPOSE_PROJECT_NAME}/proxy:template
    hostname: reverseproxy
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - ssl_dhparam:/etc/nginx/ssl/
    networks:
      proxy_net:
        aliases:
          - ${PROXY_HOST}
      app_net:
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL
    environment:
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
      ACTIVATE: 0
    depends_on:
      # NOTE: you have to rewrite all depends_on in a new yml file
      # at the moment they do not cumulate
      - backend
      # - frontend

  ###################
  ###  DATABASES  ###
  ###################
  postgres:
    image: postgres:9.6
    volumes:
      - sqldata:/var/lib/postgresql/data
      - ../submodules/builds_base/postgres/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh:ro
    environment:
      ACTIVATE: 0
      POSTGRES_USER: "${PLACEHOLDER}"
      POSTGRES_PASSWORD: "${PLACEHOLDER}"
      POSTGRES_DBS: ${PLACEHOLDER}
    networks:
      db_net:
        aliases:
          - ${ALCHEMY_HOST}

  neo4j:
    image: neo4j:3.2.1
    volumes:
      - graphdata:/data
    networks:
      db_net:
        aliases:
          - ${GRAPHDB_HOST}
    environment:
      ACTIVATE: 0
      NEO4J_AUTH: neo4j/${PLACEHOLDER}
      # NEO4J_dbms_memory_pagecache_size: 2048M
      # NEO4J_dbms_memory_heap_maxSize: 4096M
    # ports:
    #   - 9090:7474
    #   - 7687:7687

  mongodb:
    image: mongo:3.4
    volumes:
      - mongodata:/data/db
    networks:
      db_net:
        aliases:
          - ${MONGO_HOST}
    environment:
      ACTIVATE: 0

  #########################
  ###  QUEUE MANAGEMENT ###
  #########################

  celery:
    build: ../submodules/builds_base/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:template
    # hostname: celworker
    # command: celery worker -c 1 -A rapydo.flask_ext.flask_celery.worker.celery_app
    user: root
    working_dir: /code
    environment:
      ACTIVATE: 0
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      # FIXME: UHM, what is this?
      # Base code
      - ../submodules/backend:/code
      # Vanilla code
      - ../projects/${COMPOSE_PROJECT_NAME}/backend:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
    networks:
      db_net:
      worker_net:
    depends_on:
      - rabbit
      # - flower

  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      worker_net:
        aliases:
          - ${CELERY_BROKER_HOST}
    environment:
      ACTIVATE: 0

  ##########################
  ### SERVICE INTERFACES ###
  ##########################

  celeryui:
    build: ../submodules/builds_base/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:template
    hostname: flower
    user: root
    working_dir: /code
    command: start_flower
    expose:
      - 5555
    ports:
      - 5555:5555
    environment:
      ACTIVATE: 0
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      - ..:/code/${COMPOSE_PROJECT_NAME}
      - ../tmp_irods_certificates:/opt/certificates
      - ../tmp_files:/uploads
    networks:
      db_net:
      worker_net:
    depends_on:
      - rabbit

  swaggerui:
    build: ../submodules/builds_base/swaggerui
    image: ${COMPOSE_PROJECT_NAME}/swaggerui:template
    environment:
      ACTIVATE: 0

  sqlalchemyui:
    build: ../submodules/builds_base/sqlalchemyui
    image: ${COMPOSE_PROJECT_NAME}/sqlalchemyui:template
    # NOTE: this image let you access sqllite/postgres/mysql
    # with a phpmyadmin-like web page
    networks:
      db_net:
    environment:
      ACTIVATE: 0

  mongoui:
    image: mongo-express:0.40.0
    environment:
      ACTIVATE: 0
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
    networks:
      db_net:

  #############
  # REST API client (wget, curl, httpie, http-prompt)
  restclient:
    build: ../submodules/builds_base/restclient
    image: ${COMPOSE_PROJECT_NAME}/restclient:template
    hostname: rapydo_client
    environment:
      MAIN_ENDPOINT: ${API_MAIN_ENDPOINT}
      ACTIVATE: 0
    volumes:
      - ../projects/${COMPOSE_PROJECT_NAME}/project_configuration.yaml:/code/custom.yml
      - ../submodules/utilities/rapydo/utils/defaults.yaml:/code/base.yml


  ###################
  ### FTP SERVER  ###
  ###################
  ftp:
    # image: stilliard/pure-ftpd:latest
    build: ../submodules/builds_base/ftp
    image: ${COMPOSE_PROJECT_NAME}/ftp:template
    volumes:
      - pureftpd:/etc/pure-ftpd/passwd
  # /etc/ssl/private/ A directory containing a single pure-ftpd.pem file
  # with the server's SSL certificates for TLS support. Optional TLS is
  # automatically enabled when the container finds this file on startup.
    environment:
      ACTIVATE: 0
      PUBLICHOST: ${PROJECT_DOMAIN}
      ADDED_FLAGS: -d -d
    networks:
      ftp_net:

  ######################################################
  ###  iRODS iCAT server (usually for EUDAT B2safe)  ###
  ######################################################
  icat:
    # B2safe instance on irods
    build: ../submodules/builds_base/icat
    image: ${COMPOSE_PROJECT_NAME}/icat:template
    # image: b2safe:rapydo
    hostname: ${IRODS_HOST}
    # command: sleep infinity
    environment:
      ACTIVATE: 0
      POSTGRES_HOST: ${PLACEHOLDER}
      POSTGRES_USER: ${PLACEHOLDER}
      POSTGRES_PASSWORD: ${PLACEHOLDER}
      IRODS_HOST: ${PLACEHOLDER}
      IRODS_PORT: ${PLACEHOLDER}
      IRODS_ZONE: ${PLACEHOLDER}
      IRODS_DB: ${PLACEHOLDER}
      IRODS_USER: ${PLACEHOLDER}
      IRODS_PASSWORD: ${PLACEHOLDER}
    networks:
      i_net:
        aliases:
          - ${IRODS_HOST}
      db_net:
    depends_on:
      - postgres

  # #################################
  # OTHERS
  # #################################

  #######################
  # elasticsearch:
  #   image: elasticsearch
  #   hostname: elastic
  #   volumes:
  #       - restangulask_graphbased_elasticdata:/usr/share/elasticsearch/data

  #################################
  # SMTP server
  # smtp:
  #   image: namshi/smtp
  #   environment:
  #     # GMAIL_USER: -
  #     # GMAIL_PASSWORD: -
  #     - SMARTHOST_ADDRESS=mail.cineca.it
  #     - SMARTHOST_PORT=587
  #     - SMARTHOST_USER=m.dantonio
  #     - SMARTHOST_PASSWORD=-
  #     - SMARTHOST_ALIASES=*.cineca.it

  #################################
  # REDIS key/value store
  # redisqueue:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   hostname: myqueue
  #   volumes:
  #     - redisdata:/data
