os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker
env:
- PROJECT=b2stage
# - PROJECT=seadata

install:
# - data/scripts/prerequisites.sh
- pip install -r projects/${PROJECT}/requirements.txt
- chmod -R o+Xw projects # fix permissions for coverage to be computed

script:
# - /bin/bash templates/create_testing_projectrc.sh 
- TESTING=1 rapydo --project ${PROJECT} init
- rapydo pull
- rapydo start
- rapydo shell backend --command 'restapi tests --wait'

