
#############################
# config
language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
python:
    - 3.6.1
services:
    - docker
env:
    - PROJECT=eudat

#############################
# installation
before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
    - pip install --upgrade -r projects/$PROJECT/requirements.txt

#############################
# do your things
script:
    # check versions
    - docker --version
    - docker-compose --version
    - pip freeze | grep docker
    - pip search rapydo-

    - rapydo init
    - rapydo start
    # FIXME: avoid sleep with some real init here
    - sleep 60 && rapydo shell backend --command initialize
    - rapydo shell backend --command testwithcoverage
