
language: python
sudo: required
# group: legacy
# TO BE TESTED
dist: trusty
python:
  # - "3.5-dev"
  - "3.6.1"
services:
  - docker
env:
  - PROJECT=eudat

before_install:
  # update docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  # note: this will also upgrade docker compose
  - pip install --upgrade -r projects/$PROJECT/requirements.txt

# before_script:
#   - sleep 1

script:
  - docker -v
  # - docker-compose -v
  # - rapydo --version
  - pip search rapydo- && pip freeze | grep docker && pip freeze | grep requests
  # BUG FIX: ValueError: Timeout value connect was Timeout
  - pip install requests==2.11.1

  # Clone subrepos
  - rapydo init

  # FIRST THING PULL LATEST VERSION OF rapydo/core
  # NOTE: this is a fork from rapydo/core
  # - git fetch upstream && git merge upstream master

  # start the debug environment, and wait for initialization
  - rapydo control start
  - sleep 60 && rapydo --services backend shell --command initialize
  # - rapydo --services postgres log
  # - rapydo --services backend log

  # launch all unittests
  - rapydo --services backend shell --command testwithcoverage
  # - rapydo --services backend shell --command "/bin/bash -c 'testwithcoverage'"

# after_success:
# TODO: fix problems with computing coverage
#   - coveralls
