
#############################
# config
language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
python:
    - 3.6.1
services:
    - docker
env:
    - PROJECT=eudat

#############################
# installation
before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
    - pip install --upgrade -r projects/$PROJECT/requirements.txt

#############################
# do your things
script:
    - docker -v
    - pip freeze | grep docker
    - pip search rapydo-
    - pip freeze | grep requests
    - pip install requests==2.11.1
    # TODO: write a .projectrc for --project option
    - rapydo init
    - rapydo start
    # FIXME: check if sleep can be avoided
    - sleep 60 && rapydo shell backend --command initialize
    - rapydo shell backend --command testwithcoverage
