language: python
sudo: required
# dist: trusty
# group: deprecated-2017Q2
python:
# - 3.6.3
- 3.6
services:
- docker
env:
- PROJECT=b2stage
- PROJECT=seadata
# - TESTING_MODE=1

install:
- data/scripts/prerequisites.sh
- chmod -R o+Xw projects # fix permissions for coverage to be computed

script:
- docker --version && docker-compose --version
- pip list --format columns | grep docker && pip search rapydo-

# set TESTING mode
#- sed -i "9s/0/1/" projects/${PROJECT}/confs/debug.yml
# test anonymous (IRODS_ANONYMOUS / ENABLE_PUBLIC_ENDPOINT)
#- sed -i "39s/0/1/" projects/${PROJECT}/project_configuration.yaml
#- sed -i "40s/0/1/" projects/${PROJECT}/project_configuration.yaml

- touch .projectrc
- cat <<EOF > .projectrc
project: ${PROJECT}
development: True
project_configuration:
  variables:
    env:
      IRODS_ANONYMOUS: 1
      ENABLE_PUBLIC_ENDPOINT: 1
      ACTIVATE_TESTING_MODE: 1
EOF

- rapydo init
- rapydo pull
- rapydo start
- rapydo shell backend --command 'restapi tests --wait'

# coverage within a docker container
after_success:
- rapydo --log-level VERBOSE coverall
