os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker
env:
- PROJECT=b2stage
# - PROJECT=seadata

install:
- data/scripts/prerequisites.sh
- chmod -R o+Xw projects # fix permissions for coverage to be computed

script:
- docker --version && docker-compose --version
- pip list --format columns | grep docker && pip search rapydo-

# - /bin/bash templates/create_testing_projectrc.sh 
- rapydo --project ${PROJECT} init
- rapydo pull
- rapydo start
- rapydo shell backend --command 'restapi tests --wait'

