
language: python
sudo: required
# https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against
python:
  - "3.6.1"
services:
  - docker

before_install:
  # update docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  # note: this will also upgrade docker compose
  - pip install --upgrade -r requirements.txt

# before_script:
#   - sleep 1

script:
  - docker -v
  - docker-compose -v
  - rapydo --version

  # Clone, download, build
  - rapydo init

  # needed to let the system create files with test coverage
  - chmod o+w backend

  # build docker images
  - rapydo build

  # start the debug environment, and wait for initialization
  - rapydo control start

  # launch all unittests
  - sleep 20
  - rapydo shell --command "/bin/bash -c 'testwithcoverage'"

  # # client shell?
  # rapydo --services restclient shell --user developer

after_success:
  - coveralls
