language: python
sudo: required
python:
  - "3.4"
services:
  - docker
  #- docker-compose
install:
  # - sudo apt-get update
  
script:
  - docker -v
  - docker-compose -v
  #- scripts/run.sh init
  #- scripts/run.sh graceful
  #- docker exec httpapi_rest_1 nosetests
