os: linux
dist: bionic
language: python
python:
  - 3.8
services:
  - docker
env:
  - PROJECT=b2stage
# - PROJECT=seadata

script:
  - pip install git+https://github.com/rapydo/do.git@0.9
  - rapydo --testing --project ${PROJECT} -e ACTIVATE_SMTP=0 init
  - rapydo pull
  - rapydo build
  - rapydo start
  - sleep 20
  - rapydo logs
  - rapydo shell backend --command 'restapi tests --wait'
