language: python
sudo: required
python:
  - "3.4"
services:
  - docker
  #- docker-compose

env:
  DOCKER_COMPOSE_VERSION: 1.6.2
  
before_install:  
  # update docker
  - sudo apt-get update
  - yes | sudo apt-get install docker-engine
  
  # update docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
install:
  # - sudo apt-get update
  
script:
  - docker -v
  - docker-compose -v
  #- scripts/run.sh init
  #- scripts/run.sh graceful
  #- docker exec httpapi_rest_1 nosetests
