
#############################
# config
language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
python:
- 3.6.1
services:
- docker
env:
- PROJECT=eudat

#############################
# installation
before_install:
- sudo apt-get update
- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
- data/scripts/prerequisites.sh
# fix permissions for coverage to be computed
- chmod -R o+Xw projects

#############################
# do your things
script:
# check versions
- docker --version
- docker-compose --version
- pip freeze | grep docker
- pip search rapydo-

- rapydo init
- rapydo start && sleep 30  # sleep a few seconds to get the db initialized
- rapydo shell backend --command 'restapi tests'

# coverage within a docker container
after_success:
- docker cp ${PROJECT}_backend_1:/code/.coverage .
- ln -s projects/$PROJECT/backend $PROJECT
- docker run -it -v $(pwd):/repo -w /repo $PROJECT/backend:template coveralls
