language: python
sudo: required
python:
  - "3.6"
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.10.0

before_install:
  # update docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # update docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip install coveralls python-coveralls --upgrade

# before_script:
#   - chmod o+w backend

script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  # - docker-compose run test
  - ./do update
  - ./do init
  # needed to let the system create files with test coverage
  - chmod o+w backend
  - ./do DEBUG
  - ./do api_test

after_success:
  - coveralls
