language: python
sudo: required
# https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against
python:
  - "3.6.1"
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

before_install:
  # update docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # # update docker-compose
  # - sudo rm /usr/local/bin/docker-compose
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - sudo mv docker-compose /usr/local/bin

install:
  # note: this will also upgrade docker compose
  - pip install --upgrade -r requirements.txt

# before_script:
#   - chmod o+w backend

script:
  - docker -v
  - docker-compose -v
  - rapydo --version

  # Clone, download, build
  # - ./do update
  - rapydo init
  - rapydo check

  # needed to let the system create files with test coverage
  - chmod o+w backend

  # build docker images
  - rapydo build

  # start the debug environment, and wait for initialization
  - rapydo start
  # - ./do DEBUG await

  # launch all unittests
  - sleep 20
  - rapydo shell --command "/bin/bash -c 'testwithcoverage'"

  # # client shell?
  # rapydo --services restclient shell --user developer

after_success:
  - coveralls
