site_name: REST API automatic mock
pages:
- Introduction: index.md
- Quick start: quick.md
- Configuration: conf.md
- Run the server: run.md
- Manage APIs: manage.md
- Security: security.md
theme: journal