version: '3'

volumes:
  localdata:
    driver: local

services:

  backend:
    restart: on-failure:5
    # TO TEST the failure:
    # 1. go inside backend
    # 2. ps aux --forest
    # 3. kill process 1 and the tree branches

    # restart: always
    # command: sleep infinity
    environment:
      ##################
      # Base info
      # ACTIVATE: 1
      APP_MODE: production
      # FLASK_DEBUG: 0
      DEBUG_LEVEL: INFO
      NGINX_ACTIVE: "True"

      ##################
      # EUDAT RELATED
      ## /api/login is not enabled in production
      MAIN_LOGIN_ENABLE: 0
      ## If you don't provide credentials b2access will not be enabled
      # B2ACCESS_ENV: production
      # B2ACCESS_ENV: staging
      # B2ACCESS_ENV: development
      B2ACCESS_ENV: ${B2ACCESS_ENV}

      # SEADATA CELERY
      CELERY_ENABLE: ${SEADATA_PROJECT}
      CELERY_EXTERNAL: 1
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BROKER_HOST: ${CELERY_BROKER_HOST}
      CELERY_BROKER_PORT: ${CELERY_BROKER_PORT}
      CELERY_BROKER_USER: ${CELERY_BROKER_USER}
      CELERY_BROKER_PASSWORD: ${CELERY_BROKER_PASSWORD}
      CELERY_BROKER_VHOST: ${CELERY_BROKER_VHOST}

      CELERY_BACKEND: ${CELERY_BACKEND}
      CELERY_BACKEND_HOST: ${CELERY_BACKEND_HOST}
      CELERY_BACKEND_PORT: ${CELERY_BACKEND_PORT}
      CELERY_BACKEND_USER: ${CELERY_BACKEND_USER}
      CELERY_BACKEND_PASSWORD: ${CELERY_BACKEND_PASSWORD}

      # SEADATA ELASTIC LOGS
      # ELASTIC_ENABLE: ${SEADATA_PROJECT}
      # ELASTIC_EXTERNAL: 1
      # ELASTIC_HOST: ${ELASTIC_HOST}
      # ELASTIC_PORT: ${ELASTIC_PORT}

      ##################
    depends_on:
      # - icat
      - postgres
    # talk only to proxy
    expose:
      - 8080
    volumes:
      # B2HANDLE credentials to solve PID metadata in write mode
      - ${VANILLA_DIR}/data/b2handle:${HANDLE_CREDENTIALS_INTERNAL_PATH}
    #   # FIX missing IP / DNS
    #   - ${VANILLA_DIR}/projects/b2stage/builds/backend/fixip.sh:/docker-entrypoint.d/fixip.sh
    #   # # DEBUG modifications on submodules
    #   # - ${SUBMODULE_DIR}/http-api/restapi:/usr/local/lib/python3.6/dist-packages/restapi

  postgres:
    # restart: always
    restart: on-failure:5
    # Activate a production ready configuration
    volumes:
      # - ${SUBMODULE_DIR}/build-templates/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ${SUBMODULE_DIR}/build-templates/postgres/pgs_prod.sh:/docker-entrypoint-initdb.d/init-production.conf.sh:ro

  proxy:
    restart: always
    environment:
      ACTIVATE: 1
      # DOMAIN: ${PROJECT_DOMAIN}
      # MODE: ${LETSENCRYPT_MODE}
    volumes:
      # SSL / HTTPS
      # - letsencrypt_certs:/etc/letsencrypt
      - ${SUBMODULE_DIR}/rapydo-confs/confs/nginx/production_nofrontend.conf:/etc/nginx/sites-enabled/production
      # 502 Bad Gateway
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/proxy/badgateway.html:/usr/share/nginx/html/custom_502.html
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL

  # if using self signed certificates
  # and trying to test locally:
  restclient:
    environment:

      # ACTIVATE: 1
      ACTIVATE: 0 # change for debugging

      APP_HOST: --verify /tmp/certs/real/fullchain1.pem https://${PROJECT_DOMAIN}
      APP_PORT:
      DOMAIN: ${PROJECT_DOMAIN}
      PROXY_HOST: ${PROXY_HOST}
      IRODS_GUEST_USER: ${IRODS_USER}
    networks:
      proxy_net:
    depends_on:
      - proxy
    volumes:
      - letsencrypt_certs:/tmp/certs

  ################
  icat:
    command: /docker-entrypoint.d/b2access.sh
    # command: echo enabled b2access certificates
    volumes:
      # B2ACCESS certificates
      - sharedcerts:/opt/certificates
      - ${SUBMODULE_DIR}/build-templates/b2safe/extra_b2access.sh:/docker-entrypoint.d/b2access.sh
      - ${SUBMODULE_DIR}/build-templates/b2safe/b2access_certificates:${B2ACCESS_CAS}
    environment:
      ## Activate this container only if B2ACCESS will be used
      ## In python if B2ACCESS_SECRET is empty string -> False
      ## if string with chars -> True
      ACTIVATE: ${B2ACCESS_SECRET}
      B2ACCESS_CAS: ${B2ACCESS_CAS}
      ## Warning: fake variables;
      ## icat is needed only to produce the b2access certificates
      POSTGRES_HOST: null
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
      IRODS_HOST: null
      IRODS_PORT: null
      IRODS_USER: null
      IRODS_ZONE: null
      IRODS_DB: null
      IRODS_PASSWORD: null
  ################
