version: "3"

volumes:
  localdata:
    driver: local

services:
  backend:
    volumes:
      # B2HANDLE credentials to solve PID metadata in write mode
      - ${VANILLA_DIR}/data/b2handle:${HANDLE_CREDENTIALS_INTERNAL_PATH}

  icat:
    command: /docker-entrypoint.d/b2access.sh
    # command: echo enabled b2access certificates
    environment:
      ## Activate this container only if B2ACCESS will be used
      ## In python if B2ACCESS_SECRET is empty string -> False
      ## if string with chars -> True
      ACTIVATE: ${B2ACCESS_SECRET}
      B2ACCESS_CAS: ${B2ACCESS_CAS}
      ## icat is needed only to produce the b2access certificates
      POSTGRES_HOST: null
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
      IRODS_HOST: null
      IRODS_PORT: null
      IRODS_USER: null
      IRODS_ZONE: null
      IRODS_DB: null
      IRODS_PASSWORD: null
  ################
