
version: '2'

services:

  mongo:
    image: mongo
    command:
    - mongod
    - --smallfiles
    - --oplogSize
    - '128'
    volumes:
    - mongo_data:/data/db
    labels:
      # io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host_type=rocket

  rocketchat:
    image: rocketchat/rocket.chat:0.59.6
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      ROOT_URL: https://seadata-chat.yourdomain.com
      PORT: '3000'
    volumes:
    - rocket_files:/app/bundle/files
    # - b2stage_letsencrypt_certs:/tmp/certs
    links:
    - mongo:mongo
    # ports:
    # - "80:3000"
    labels:
      main: '1'
      io.rancher.scheduler.affinity:host_label: host_type=rocket

  proxy:
    image: rapydo/proxy:rocket
    hostname: proxy
    environment:
      # if empty selfsign certs are not produced
      DOMAIN: seadata-chat.yourdomain.com
      MODE: ''
    stdin_open: true
    volumes:
    - letsencrypt_certs:/etc/letsencrypt
    - ssl_dhparam:/etc/nginx/ssl
    # - /path/to/production_nofrontend.conf:/etc/nginx/sites-enabled/production
    # domainname: seadata-chat.somesite.it
    tty: true
    links:
    - rocketchat:rc
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.start_once: 'true'
      # io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host_type=rocket

  # hubot:
  #   image: rocketchat/hubot-rocketchat
  #   environment:
  #     BOT_NAME: catbot
  #     EXTERNAL_SCRIPTS: hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  #     ROCKETCHAT_PASSWORD: ichADZZwWrEMouu$$8n3M@hKu2b3,TFL49h8
  #     ROCKETCHAT_ROOM: ALL
  #     ROCKETCHAT_URL: rocketchat:3000
  #     ROCKETCHAT_USER: rocket.cat
  #   labels:
  #     io.rancher.scheduler.affinity:host_label: host_type=rocket
  #   links:
  #   - rocketchat:rocketchat
  #   ports:
  #   - 3001:8080/tcp
