
version: '2'
services:
  mongo:
    scale: 1
    start_on_create: true
  rocketchat:
    scale: 1
    start_on_create: true
  proxy:
    scale: 0
    start_on_create: true
  # hubot:
  #   scale: 0
  #   start_on_create: true
