version: '3'
#######################
# Link services inside API

services:
  backend:
    environment:
      - APP_MODE=production
      - DEBUG_LEVEL=INFO
      - NGINX_ACTIVE=true

    networks:
      proxy_net:
        aliases:
          - ${API_HOST}

    expose:
      - 8080

  frontend:
    environment:
      APP_MODE: production
    networks:
      proxy_net:
        aliases:
          - html

  proxy:
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - ssl_dhparam:/etc/nginx/ssl/
    environment:
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}

    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

volumes:
  letsencrypt_certs:
    driver: local
  ssl_dhparam:
    driver: local

# networks:
#   proxy_net: