
backend:
  user: root
  command: init
  # command: sleep infinity
  environment:
    - UWSGI_MASTER=/tmp/uwsgi/starter.ini
    - NGINX_ACTIVE=true
  volumes:
    - ../containers/wsgi:/tmp/uwsgi
    # - nginx_empty_sites:/etc/nginx/sites-enabled
    - ../containers/nginx_internal:/etc/nginx/conf.d
    # - ./app:/code

frontend:
  # command: sleep infinity
  links:
    - backend:myapi

proxy:
  volumes:
    - letsencrypt_certs:/etc/letsencrypt
    - ssl_dhparam:/etc/nginx/ssl/
  links:
    - backend:api
    - frontend:html
  ports:
    - 80:80
    - 443:443
