
version: '3'
services:

  proxy:
    volumes:
      # SSL / HTTPS
      - ./confs/prod_proxy.conf:/etc/nginx/sites-enabled/production
    ports:
      - 80:80
      - 443:443

  rest:
    user: root
    # set the home to the main internal 'irods' unix user
    # otherwise `uwsgi` will try to write inside the /root homedir
    command: /bin/bash -c "HOME=/home/irods init"
    # command: sleep infinity
    environment:
      APP_MODE: production
      DEBUG_LEVEL: INFO
  ##################
  # Enable debug in our first prototype

  ## TO BE REMOVED
      API_DEBUG: "true"
  ## TO BE REMOVED
  ##################
      UWSGI_MASTER: /tmp/uwsgi/uwsgi_starter.ini
      NGINX_ACTIVE: "True"
    volumes:
      - ./confs/uwsgi:/tmp/uwsgi
      - ./confs/nginx_internal:/etc/nginx/conf.d
    # ports:
    #   - 8080:8080

  # # if using self signed certificates
  # # and trying to test locally:
  # client:
  #   volumes:
  #     # - ./certs/nginx-selfsigned.crt:/tmp/cert.crt
  #     - sslcerts:/tmp/certs
  #   links:
  #     - proxy:awesome.docker
  #     # - proxy:USEYOURDOMAINNAME
