
proxy:
  #################
  # SSL / HTTPS
  volumes:
    - ./confs/prod_proxy.conf:/etc/nginx/sites-enabled/production
    - ./certs/nginx-selfsigned.key:/etc/nginx/server.key
    - ./certs/nginx-selfsigned.crt:/etc/nginx/server.crt
    # # LET'S ENCRYPT!
    # - ./certs/b2stage.cineca.it:/etc/letsencrypt/real
  ports:
    - 80:80
    - 443:443
  #################
  links:
    - rest:restapi

rest:
  user: root
  # set the home to the main internal irods user
  # otherwise it will try to write insie the /root homedir
  command: /bin/bash -c "HOME=/home/irods init"
  # command: sleep infinity
  environment:
    APP_MODE: production
##################
# Enable debug in our first prototype

## TO BE REMOVED
    API_DEBUG: "true"
## TO BE REMOVED
##################
    UWSGI_MASTER: /tmp/uwsgi/uwsgi_starter.ini
    NGINX_ACTIVE: "True"
  volumes:
    - ./confs/uwsgi:/tmp/uwsgi
    - ./confs/nginx_internal:/etc/nginx/conf.d
  # ports:
  #   - 8080:8080
  links:
    # IRODS MUST BE CALLED rodserver
    - icat:rodserver
    # # GRAPHDB MUST BE CALLED gdb
    # - graphdb:gdb

apitests:
  volumes:
    - ./certs/nginx-selfsigned.crt:/tmp/cert.crt
  links:
    # - rest:apiserver
    - proxy:awesome.docker
    # - proxy:USEYOURDOMAINNAME
    # - proxy:b2stage.cineca.it
