
version: '3'
services:

  proxy:
    environment:
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
    volumes:
      # SSL / HTTPS
      - ./confs/prod_proxy.conf:/etc/nginx/sites-enabled/production
      - sslcerts:/etc/letsencrypt
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL

  rest:
    # user: root
    # # set the home to the main internal 'irods' unix user
    # # otherwise `uwsgi` will try to write inside the /root homedir
    # command: /bin/bash -c "HOME=/home/irods init"
    # # command: sleep infinity
    environment:
      APP_MODE: production
      DEBUG_LEVEL: INFO
      NGINX_ACTIVE: "True"
      # UWSGI_MASTER: /tmp/uwsgi/uwsgi_starter.ini
    # volumes:
    #   - ./confs/uwsgi:/tmp/uwsgi
    #   # - ./confs/nginx_internal:/etc/nginx/conf.d
    expose:
      - 8080

  # # # if using self signed certificates
  # # # and trying to test locally:
  # client:
  #   environment:
  #     APP_HOST: ${PROXY_HOST}
  #     APP_PORT: ${PROXY_DEV_PORT}
  #   networks:
  #     proxy_net:
  #   depends_on:
  #     - proxy
  # # client:
  # #   volumes:
  # #     # - ./certs/nginx-selfsigned.crt:/tmp/cert.crt
  # #     - sslcerts:/tmp/certs
  # #   links:
  # #     - proxy:awesome.docker
  # #     # - proxy:USEYOURDOMAINNAME
