
rest:
  environment:
    APP_MODE: production
  links:
    # IRODS MUST BE CALLED rodserver
    - icat:rodserver
    # # GRAPHDB MUST BE CALLED gdb
    # - graphdb:gdb

proxy:
  #################
  # SSL / HTTPS
  volumes:
    - ./confs/prod_proxy.conf:/etc/nginx/sites-enabled/production
    - ./certs/nginx-selfsigned.key:/etc/nginx/server.key
    - ./certs/nginx-selfsigned.crt:/etc/nginx/server.crt
  ports:
    - 80:80
    - 443:443
  #################
  links:
    - rest:restapi

apitests:
  volumes:
    - ./certs/nginx-selfsigned.crt:/tmp/cert.crt
  links:
    - proxy:awesome.docker
