version: '3'
services:

  backend:
    # command: sleep infinity
    environment:
      APP_MODE: production
      DEBUG_LEVEL: INFO
      NGINX_ACTIVE: "True"
      # EUDAT RELATED
      # B2ACCESS_ENV: production
      B2ACCESS_ENV: development  # to be fixed
    depends_on:
      - sql
    expose:
      - 8080

  proxy:
    environment:
      DOMAIN: ${PROJECT_DOMAIN}
      MODE: ${LETSENCRYPT_MODE}
    volumes:
      # SSL / HTTPS
      - ../containers/confs/nginx/production.conf:/etc/nginx/sites-enabled/production
      - sslcerts:/etc/letsencrypt
    ports:
      - ${PROXY_DEV_PORT}:${PROXY_DEV_PORT}   # 80 redirect
      - ${PROXY_PROD_PORT}:${PROXY_PROD_PORT} # 443 SSL

  # if using self signed certificates
  # and trying to test locally:
  restclient:
    environment:
      APP_HOST: --verify /tmp/certs/real/fullchain1.pem https://${PROJECT_DOMAIN}
      APP_PORT:
      DOMAIN: ${PROJECT_DOMAIN}
      PROXY_HOST: ${PROXY_HOST}
    networks:
      proxy_net:
    depends_on:
      - proxy
    volumes:
      - sslcerts:/tmp/certs
