
version: '2'
services:
  queue:
    image: rabbitmq:3.7.5-management-alpine
    hostname: rabbit
    # environment:
    #   RABBITMQ_DEFAULT_USER: admin_user
    #   RABBITMQ_DEFAULT_PASS: my_random_pw
    volumes:
      - /var/nfs/general/rabbit:/var/lib/rabbitmq
    labels:
      io.rancher.scheduler.affinity:host_label: host_type=nfs
    ports:
      - 4369:4369 # open firewall internally
      - 5672:5672 # open firewall internally
      - 9999:15672 # open firewall to your workstation
