# ###############################################
# Copyright 2011-2017 EUDAT CDI - www.eudat.eu
# ###############################################

project:
  title: EUDAT-B2HOST queue of workers
  description: Processing tasks in the cloud
  version: 0.1.0

# environment configuration
variables:
  env:
    B2STAGE_PROJECT: b2stage
    RABBITMQ_USER: whiterabbit
    RABBITMQ_PASSWORD: downthehole

# Keep track of releases and dependencies
releases:
  '0.1.0':
    type: alpha
    rapydo: 0.6.1
    status: developing

# controller:
#   commands:
#     some_command:
#       command: echo hello
#       service: celery
#       user: root
