# ###############################################
# Copyright 2011-2017 EUDAT CDI - www.eudat.eu
# ###############################################

project:
  title: EUDAT-B2SAFE 'dockerized' server
  description: Processing files in different EUDAT domains
  version: v0.1.0
  rapydo: 0.5.6

###############################
## Please CHECK VARIABLES here
## before starting your project
###############################
variables:

  env:

    IRODS_USER: irods
    IRODS_GUEST_USER: guest              # intended to work only with GSI
    IRODS_DEFAULT_ADMIN_USER: rodsminer  # intended to work only with GSI
    IRODS_ZONE: tempZone
    IRODS_HOME: home
    IRODS_AUTHSCHEME:   # to be auto-detected
    # IRODS_AUTHSCHEME: credentials
    # IRODS_AUTHSCHEME: GSI
    # NOTE: this must match ALCHEMY_PASSWORD
    IRODS_PASSWORD: chooseapasswordwisely
    IRODS_DB: ICAT
    IRODS_CHUNKSIZE: 1048576

    # Postgres configuration:
    ALCHEMY_USER: rods
    ALCHEMY_PASSWORD: chooseapasswordwisely
    ALCHEMY_DBS: ICAT
    ALCHEMY_API_DB:

    # B2access certificates path
    B2ACCESS_CAS: /tmp/certificates/b2access

controller:
  commands:
    irods_restart:
      description: Try to restart the current iCAT server instance
      command: service irods restart
      service: icat
      user: root

# Keep track of releases and dependencies
releases:
  '0.5.1':
    type: beta
    rapydo: null
    status: released
  '0.5.2':
    type: beta
    rapydo: null
    status: discontinued
  '0.6.0':
    type: RC1
    rapydo: 0.5.3
    status: released
  '0.6.1':
    type: RC2
    rapydo: 0.5.4
    status: released
  '0.6.2':
    type: RC3
    rapydo: 0.5.6
    status: developing
  '1.0.0':
    type: stable
    # rapydo: 0.5.7
    rapydo: null
    status: todo
