
version: '3'
services:

  icat:
    build:
      context: ../submodules/build-templates/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    # image: ${COMPOSE_PROJECT_NAME}/server:b2safe-mod
    image: rapydo/b2safe:${RAPYDO_VERSION}
    environment:
      B2ACCESS_CAS: ${B2ACCESS_CAS}

    volumes:
      - ../submodules/build-templates/b2safe/extra_b2access.sh:/docker-entrypoint.d/b2access.sh
      - ../submodules/build-templates/b2safe/extra_b2safe.sh:/docker-entrypoint.d/b2safe.sh
      # B2ACCESS dev and prod certificates
      - ../submodules/build-templates/b2safe/b2access_certificates:${B2ACCESS_CAS}
      # # Extra volumes
      # - /your/path/to/something:/var/lib/data/irods

    # Open irods port to Outside world
    ports:
        - 1247:1247
