
version: '3'
services:

  icat:
    build:
      context: ${SUBMODULE_DIR}/build-templates/b2safe
      # args:
      #   RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/b2safe:${RAPYDO_VERSION}
    environment:
      B2ACCESS_CAS: ${B2ACCESS_CAS}

    volumes:
      - ${SUBMODULE_DIR}/build-templates/b2safe/extra_b2access.sh:/docker-entrypoint.d/b2access.sh
      - ${SUBMODULE_DIR}/build-templates/b2safe/extra_b2safe.sh:/docker-entrypoint.d/b2safe.sh
      # B2ACCESS dev and prod certificates
      - ${SUBMODULE_DIR}/build-templates/b2safe/b2access_certificates:${B2ACCESS_CAS}
      # # Extra volumes
      # - /your/path/to/something:/var/lib/data/irods

    # Open irods port to Outside world
    ports:
        - 1247:1247
