version: '3'

volumes:
  etcconf:
    driver: local
  irodscerts:
    driver: local
  irodshome:
    driver: local
  irodsvar:
    driver: local

services:
  postgres:
    environment:
      POSTGRES_USER: "${ALCHEMY_USER}"
      POSTGRES_PASSWORD: "${ALCHEMY_PASSWORD}"
      POSTGRES_DBS: ${ALCHEMY_DBS}
  icat:
    environment:
      ACTIVATE: 1
      POSTGRES_HOST: "${ALCHEMY_HOST}"
      POSTGRES_USER: "${ALCHEMY_USER}"
      POSTGRES_PASSWORD: "${ALCHEMY_PASSWORD}"
      IRODS_HOST: "${IRODS_HOST}"
      IRODS_PORT: ${IRODS_PORT}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_DB: "${IRODS_DB}"
      IRODS_USER: ${IRODS_USER}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_ANONYMOUS: ${IRODS_ANONYMOUS}
    volumes:
      - etcconf:/etc
      - irodshome:/home/${IRODS_USER}
      - irodsvar:/var/lib/${IRODS_USER}
      - irodscerts:/opt/certificates
    # # Open irods port to Outside world
    # ports:
    #     - 1247:1247
  sqlalchemyui:
    ports:
      - 80:8080
  iclient:
    build:
      context: ${SUBMODULE_DIR}/build-templates/icat
      # args:
      #   RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/icat:${RAPYDO_VERSION}
    hostname: iclient
    command: sleep infinity
    environment:
      ACTIVATE: 1
      IRODS_HOST: "${IRODS_HOST}"
      IRODS_PORT: ${IRODS_PORT}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_USER: ${IRODS_USER}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
    volumes:
      - irodshome:/home/${IRODS_USER}
      - irodscerts:/opt/certificates
    networks:
      i_net:
    depends_on:
      - icat
