version: '3'

services:

  icat:
    build:
      context: ../submodules/build-templates/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/icat:${RAPYDO_VERSION}
    # Open irods port to Outside world
    ports:
        - 1247:1247
