version: '3'

services:

  icat:
    build:
      context: ${SUBMODULE_DIR}/build-templates/icat
      # args:
      #   RAPYDO_VERSION: ${RAPYDO_VERSION}
    # image: rapydo/icat:${RAPYDO_VERSION}
    image: b2safe/server:icat
    # Open irods port to Outside world
    ports:
        - 1247:1247
