
project:
  title: EUDAT-B2STAGE HTTP-API server
  version: v0.6.2-rc3
  description: Processing files in different EUDAT domains

###############################
## Please CHECK VARIABLES here
## before starting your project
###############################
variables:

  env:

    ###############################
    ## Dockerized DB
    # You may leave this like this in DEBUG mode
    ALCHEMY_USER: rods
    ALCHEMY_PASSWORD: chooseapasswordwisely
    ALCHEMY_API_DB: SQL_API

    ###############################
    ## B2ACCESS
    B2ACCESS_ACCOUNT: httpapi
    B2ACCESS_SECRET: SETYOURSECRETKEY

    ###############################
    ## LOCAL iRODS server VERSION
    # NOTE: intended for DEBUG mode, to be commented in PRODUCTION
    IRODS_USER: irods
    IRODS_GUEST_USER: guest              # intended to work only with GSI
    IRODS_DEFAULT_ADMIN_USER: rodsminer  # intended to work only with GSI
    IRODS_ZONE: tempZone
    IRODS_HOME: home
    IRODS_AUTHSCHEME:   # to be auto-detected
    # IRODS_AUTHSCHEME: credentials
    # IRODS_AUTHSCHEME: GSI
    # NOTE: this must match ALCHEMY_PASSWORD if running in debug mode
    IRODS_PASSWORD: chooseapasswordwisely
    # If empty it will be automatically computed within the docker network
    IRODS_DN:

    ###############################
    ## PRODUCTION example: iRODS server VERSION

    # IRODS_HOST: eudat-dmp1
    # IRODS_ZONE: cinecaDMPZone1
    # IRODS_HOME: home
    # # You MUST provide user/password credentials to iquery users informations
    # IRODS_AUTHSCHEME: credentials
    # IRODS_USER: httpapi
    # IRODS_PASSWORD: SETTHISPASSWORDINPRODUCTION
    # # DN of your external iRODS host (with GSI plugin installed)
    # # Needed for B2ACCESS certificates exchange
    # IRODS_DN: "/C=US/O=Globus Consortium/OU=Globus Connect Service/CN=host/yourhostname.com"

###############################
## WARNING!! do not modify below
## if you don't know what you are doing
###############################

    # COMPOSE_PROJECT_NAME: eudat
    # PROJECT_DOMAIN: myserver.mydomain.dev
    AUTH_SERVICE: sqlalchemy
    # AUTH_SERVICE: mongo
    API_MAIN_ENDPOINT: registered
    # LETSENCRYPT_MODE: --staging
    LETSENCRYPT_MODE:

    IRODS_DB: ICAT
    IRODS_CHUNKSIZE: 1048576
    B2ACCESS_CAS: /tmp/certificates/b2access

    # sqlalchemy fixed:
    ALCHEMY_ENGINE: postgresql
    ALCHEMY_DBS: 'ICAT SQL_API'

    HANDLE_CREDENTIALS_INTERNAL_PATH: /opt/certificates/b2handle
    HANDLE_BASE: "https://url.to.epic/handles/"
    # HANDLE_USER:
    # HANDLE_PREFIX:
    # HANDLE_PASS:

    # # neo4j:
    # GRAPHDB_PASSWORD: wakeupneo
    # EPIC HANDLE credentials

    # ##: OTHERs / FIXED
    # FLASK_SUBNET: 175.1.0.0
    # FLASK_FIXED_IP: 175.1.0.10
    UPLOAD_PATH: /uploads
    FULL_JWT: false

  # # CHANGE ME in production
  # backend:
  #   credentials:
  #     username: someotheruser
  #     password: somepassword
  #     # warning: do not change base roles for the database
  #     roles:
  #       user: normal_user
  #       internal: staff_user
  #       admin: admin_root
  #       default: normal_user

  repos:
    utils:
      branch: 0.5.5
    backend:
      branch: 0.5.5
    build-templates:
      branch: 0.5.5
    # develop:
    #   branch: 0.5.5
    #   if: true
    irods-client:
      branch: master # python-irodsclient==0.7.0a0
      online_url: https://github.com/irods/python-irodsclient.git
      path: prc
      if: true

controller:
  commands:
    irods_restart:
      description: Try to restart the current iCAT server instance
      command: service irods restart
      service: icat
      user: root

tags:
  eudat: all endpoints associated to EUDAT services
  b2access: request/refresh authorization from B2ACCESS
  registered: upload, download, list and delete objects
  pids: resolve and download data from EUDAT Persistent IDentifier
  b2safe: proxy access to irods b2safe credentials
  # internal: for internal testing purpose only

# Keep track of releases and dependencies
releases:
  '0.5.1':
    type: beta
    rapydo: null
    status: released
  '0.5.2':
    type: beta
    rapydo: null
    status: discontinued
  '0.6.0':
    type: RC1
    rapydo: 0.5.3
    status: released
  '0.6.1':
    type: RC2
    rapydo: 0.5.4
    status: released
  '0.6.2':
    type: RC3
    rapydo: 0.5.5
    status: developing
  '0.6.3':
    type: RC4
    rapydo: null
    status: todo
  # '0.7.0':
  #   type: RC5
  #   rapydo: null
  #   status: todo
