version: '3.1'

volumes:
  mysqldata:
    driver: local

networks:
  dbs:

services:

  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      dbs:
        aliases:
          - mysqlserver

  # adminer:
  #   image: adminer:4.6.1-standalone
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     dbs:

  # ## CREATE DATABASE IF NOT EXISTS cattle
  #     COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
  # ## GRANT ALL ON cattle.* TO 'cattle'@'%' IDENTIFIED BY 'YOUR_CATTLE_DB_PASSWORD';
  # ## http://YOURIP:8080/?server=mysqlserver&username=root&sql=
  # ## $ docker-compose up -d --remove-orphans

  rancher:
    image: rancher/server:v1.6.15-rc4
    command: "--db-host mysqlserver --db-port 3306 --db-pass YOUR_CATTLE_DB_PASSWORD --db-strict-enforcing"
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      dbs:
  ## $ docker-compose logs -f rancher
  ## -e CATTLE_AGENT_IP= to own host

