---
project:
  title: My project
  description: Title of my project
variables:
  env:
    COMPOSE_PROJECT_NAME: rapydo
    PROJECT_DOMAIN: localhost
  backend: 
    credentials: 
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    enable: true
  containers: 
    users:
      backend: "root"
    authentication:
      service: "neo4j"
      # service: "relationaldb"
      username: "user@nomail.org"
      password: "test"

    authentication_service: "neo4j"