
#######################
# Link services inside API

backend:
  environment:
    BACKEND_AUTH_SERVICE: graphdb
  links:
    - gdb:gdb

# proxy:
#   links:
#     - gdb:gdb

gdb:
  ports:
  - 9090:7474
