
#######################
# Link services inside API

backend:
  volumes:
    - ..:/code/${COMPOSE_PROJECT_NAME}
  environment:
    APP_MODE: production
    DEBUG_LEVEL: INFO
    VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}

    # base the user/role mechanism on some database
    AUTH_ENABLE: 1
    # putting this here because it should not be configurable in .env
    AUTH_SERVICE: neo4j

    # # neo connection
    GRAPHDB_ENABLE: 1
    GRAPHDB_EXTERNAL: ${GRAPHDB_EXTERNAL}
    GRAPHDB_HOST: ${GRAPHDB_HOST}
    GRAPHDB_PORT: ${GRAPHDB_BOLT_PORT}
    GRAPHDB_PASSWORD: ${GRAPHDB_PASSWORD}

  links:
    - gdb:gdb

# proxy:
#   links:
#     - gdb:gdb

gdb:
  ports:
  - 9090:7474

    links:
        - mygraph:gdb
        # Redis db (as a queue) should be called queue
        # - redqueue:queue
        # RabbitMQ used as broken, shold be called queue too??
        - rabbit:queue
        - swagger:swagger
