version: "3"

services:
  icat:
    build: ${BASE_PROJECT_DIR}/builds/icat
    image: ${COMPOSE_PROJECT_NAME}/icat:${RAPYDO_VERSION}
    environment:
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      # The names of the directories in the irods zone
      # for pre-production batches, for production batches,
      # and for orders being prepared.
      SEADATA_INGESTION_COLL: ${SEADATA_INGESTION_COLL}
      SEADATA_PRODUCTION_COLL: ${SEADATA_PRODUCTION_COLL}
      SEADATA_ORDERS_COLL: ${SEADATA_ORDERS_COLL}

  rabbit:
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  backend:
    build: ${BASE_PROJECT_DIR}/builds/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    environment:
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_INGESTION_COLL: ${SEADATA_INGESTION_COLL}
      SEADATA_PRODUCTION_COLL: ${SEADATA_PRODUCTION_COLL}
      SEADATA_ORDERS_COLL: ${SEADATA_ORDERS_COLL}
      # The name of the directory in the local fs during ingestions
      # (to be mounted to celery workers and rancher containers)
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION} # host fs!
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS} # host fs!
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      SEADATA_PRIVILEGED_USERS: ${SEADATA_PRIVILEGED_USERS}
      # rancher
      RESOURCES_URL: ${RESOURCES_URL}
      RESOURCES_KEY: ${RESOURCES_KEY}
      RESOURCES_SECRET: ${RESOURCES_SECRET}
      RESOURCES_PROJECT: ${RESOURCES_PROJECT}
      RESOURCES_QCLABEL: ${RESOURCES_QCLABEL}
      RESOURCES_LOCALPATH: ${RESOURCES_LOCALPATH}
      # hub
      RESOURCES_HUB: ${RESOURCES_HUB}
      RESOURCES_HUBUSER: ${RESOURCES_HUBUSER}
      RESOURCES_HUBPASS: ${RESOURCES_HUBPASS}
      # Loggin rabbit
      RABBIT_ENABLE: ${ACTIVATE_LOGGING_RABBIT}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VHOST: ${RABBIT_VHOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      RABBIT_EXCHANGE: ${RABBIT_EXCHANGE}
      RABBIT_QUEUE: ${RABBIT_QUEUE}
      RABBIT_SSL_ENABLED: ${RABBIT_SSL_ENABLED}
      # containers
      # CONTAINERS_DBUSER: ${CONTAINERS_DBUSER}
      # CONTAINERS_DBPASS: ${CONTAINERS_DBPASS}
      # CONTAINERS_DBEXTRAUSER: ${CONTAINERS_DBEXTRAUSER}
      # CONTAINERS_DBEXTRAPASS: ${CONTAINERS_DBEXTRAPASS}
      # CONTAINERS_RABBITUSER: ${CONTAINERS_RABBITUSER}
      # CONTAINERS_RABBITPASS: ${CONTAINERS_RABBITPASS}
      CONTAINERS_WAIT_STOPPED: ${CONTAINERS_WAIT_STOPPED}
      CONTAINERS_WAIT_RUNNING: ${CONTAINERS_WAIT_RUNNING}
  # mongodb:
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}
