version: '3'

services:

  backend:
    environment:

      CELERY_ENABLE: 1
      CELERY_EXTERNAL: 1
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BROKER_HOST: ${CELERY_BROKER_HOST}
      CELERY_BROKER_PORT: ${CELERY_BROKER_PORT}
      CELERY_BROKER_USER: ${CELERY_BROKER_USER}
      CELERY_BROKER_PASSWORD: ${CELERY_BROKER_PASSWORD}
      CELERY_BROKER_VHOST: ${CELERY_BROKER_VHOST}

      CELERY_BACKEND: ${CELERY_BACKEND}
      CELERY_BACKEND_HOST: ${CELERY_BACKEND_HOST}
      CELERY_BACKEND_PORT: ${CELERY_BACKEND_PORT}
      CELERY_BACKEND_USER: ${CELERY_BACKEND_USER}
      CELERY_BACKEND_PASSWORD: ${CELERY_BACKEND_PASSWORD}

      MONGO_ENABLE: 0 

    volumes:
      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}

  postgres:
    restart: always

  mongodb:
    environment:
      ACTIVATE: 0
