# This file is obsolete

version: "3"

volumes:
  redis_cache:
    driver: local

services:
  proxy:
    environment:
      ACTIVATE: 0

  backend:
    environment:
      ACTIVATE: 0

  postgres:
    environment:
      ACTIVATE: 0

  rabbit:
    restart: always
    environment:
      ACTIVATE: ${ACTIVATE_RABBIT}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  mongodb:
    restart: always
    environment:
      ACTIVATE: ${ACTIVATE_MONGODB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: on-failure:5
    volumes:
      # configuration files
      - redis_cache:/data
    ports:
      - 6379:6379
    environment:
      ACTIVATE: ${ACTIVATE_REDIS}

  celery:
    environment:
      ACTIVATE: 0
