version: "3"

services:
  proxy:
    environment:
      ACTIVATE: 0

  backend:
    environment:
      ACTIVATE: 0

  postgres:
    environment:
      ACTIVATE: 0

  rabbit:
    environment:
      ACTIVATE: 0

  redis:
    environment:
      ACTIVATE: 0

  # rabbit:
  #   restart: always
  #   environment:
  #     ACTIVATE: ${ACTIVATE_RABBIT}
  #   ports:
  #     - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  # mongodb:
  #   restart: always
  #   environment:
  #     ACTIVATE: ${ACTIVATE_MONGODB}
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}

  celery:
    restart: on-failure:15
    build:
      context: ${BASE_PROJECT_DIR}/builds/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    command: celery -A restapi.connectors.celery.worker.celery_app worker --concurrency=1 -Ofair -Q celery -n worker-%h
    volumes:
      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}
    environment:
      CELERY_EXTERNAL: 1
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}

      REDIS_ENABLE: 1

      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}
      IRODS_EXPIRATION_TIME: ${IRODS_EXPIRATION_TIME}
      IRODS_VERIFICATION_TIME: ${IRODS_VERIFICATION_TIME}

  celeryui:
    restart: on-failure:5
    build:
      context: ${BASE_PROJECT_DIR}/builds/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    hostname: flower
    environment:
      AUTH_ENABLE: 0
      CELERY_EXTERNAL: 1
      CELERYUI_USER: ${CELERYUI_USER}
      CELERYUI_PASSWORD: ${CELERYUI_PASSWORD}
      #############################
      ACTIVATE: ${ACTIVATE_CELERYUI}
      MAIN_LOGIN_ENABLE: 0
      APP_SECRETS: ${APP_SECRETS}
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      REDIS_ENABLE: 1
      REDIS_ENABLE_CONNECTOR: ${REDIS_ENABLE_CONNECTOR}
      REDIS_EXPIRATION_TIME: ${REDIS_EXPIRATION_TIME}
      REDIS_VERIFICATION_TIME: ${REDIS_VERIFICATION_TIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}
      IRODS_EXPIRATION_TIME: ${IRODS_EXPIRATION_TIME}
      IRODS_VERIFICATION_TIME: ${IRODS_VERIFICATION_TIME}
      # SEADATA ELASTIC LOGS

  ingestion_celery:
    restart: on-failure:15
    build:
      context: ${BASE_PROJECT_DIR}/builds/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    entrypoint: docker-entrypoint-celery
    command: celery -A restapi.connectors.celery.worker.celery_app worker --concurrency=1 -Ofair -Q ingestion -n worker-%h
    # user: developer
    working_dir: /code
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/do/controller/confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${PROJECT_DIR}/project_configuration.yaml:/code/confs/project_configuration.yaml
      - letsencrypt_certs:/etc/letsencrypt
      # Vanilla code
      - ${PROJECT_DIR}/backend:/code/${COMPOSE_PROJECT_NAME}
      # From project, if any
      - ${BASE_PROJECT_DIR}/backend:/code/${EXTENDED_PROJECT}
      - ${BASE_PROJECT_DIR}/project_configuration.yaml:/code/confs/extended_project_configuration.yaml

      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}

      - ${SUBMODULE_DIR}/http-api/restapi:${PYTHON_PATH}/restapi

      - ${VANILLA_DIR}/data/logs:/logs

    networks:
      db_net:
      worker_net:
    # depends_on:
    #   - rabbit
    environment:
      CURRENT_UID: ${CURRENT_UID}
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      EXTENDED_PACKAGE: ${EXTENDED_PROJECT}
      APP_SECRETS: ${APP_SECRETS}
      CURRENT_GID: ${CURRENT_GID}

      CELERY_ENABLE: 1

      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_EXPIRATION_TIME: ${CELERY_EXPIRATION_TIME}
      CELERY_VERIFICATION_TIME: ${CELERY_VERIFICATION_TIME}
      RABBITMQ_EXPIRATION_TIME: ${RABBITMQ_EXPIRATION_TIME}
      RABBITMQ_VERIFICATION_TIME: ${RABBITMQ_VERIFICATION_TIME}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_SSL_ENABLED: ${RABBITMQ_SSL_ENABLED}

      REDIS_ENABLE: 1
      REDIS_ENABLE_CONNECTOR: ${REDIS_ENABLE_CONNECTOR}
      REDIS_EXPIRATION_TIME: ${REDIS_EXPIRATION_TIME}
      REDIS_VERIFICATION_TIME: ${REDIS_VERIFICATION_TIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      CELERY_BACKEND: ${CELERY_BACKEND}
      MONGO_EXPIRATION_TIME: ${MONGO_EXPIRATION_TIME}
      MONGO_VERIFICATION_TIME: ${MONGO_VERIFICATION_TIME}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      APP_MODE: ${APP_MODE}
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}
      IRODS_EXPIRATION_TIME: ${IRODS_EXPIRATION_TIME}
      IRODS_VERIFICATION_TIME: ${IRODS_VERIFICATION_TIME}

      SMTP_ENABLE_CONNECTOR: ${SMTP_ENABLE_CONNECTOR}
      SMTP_ENABLE: ${ACTIVATE_SMTP}
      SMTP_EXPIRATION_TIME: ${SMTP_EXPIRATION_TIME}
      SMTP_VERIFICATION_TIME: ${SMTP_VERIFICATION_TIME}
      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_NOREPLY: ${SMTP_NOREPLY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  restricted_celery:
    restart: on-failure:5
    build:
      context: ${BASE_PROJECT_DIR}/builds/backend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    image: ${COMPOSE_PROJECT_NAME}/backend:${RAPYDO_VERSION}
    entrypoint: docker-entrypoint-celery
    command: celery -A restapi.connectors.celery.worker.celery_app worker --concurrency=1 -Ofair -Q restricted -n worker-%h
    # user: developer
    working_dir: /code
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/do/controller/confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${PROJECT_DIR}/project_configuration.yaml:/code/confs/project_configuration.yaml
      - letsencrypt_certs:/etc/letsencrypt
      # Vanilla code
      - ${PROJECT_DIR}/backend:/code/${COMPOSE_PROJECT_NAME}
      # From project, if any
      - ${BASE_PROJECT_DIR}/backend:/code/${EXTENDED_PROJECT}
      - ${BASE_PROJECT_DIR}/project_configuration.yaml:/code/confs/extended_project_configuration.yaml

      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}

      - ${SUBMODULE_DIR}/http-api/restapi:${PYTHON_PATH}/restapi

      - ${VANILLA_DIR}/data/logs:/logs

    networks:
      db_net:
      worker_net:
    # depends_on:
    #   - rabbit
    environment:
      CURRENT_UID: ${CURRENT_UID}
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      EXTENDED_PACKAGE: ${EXTENDED_PROJECT}
      APP_SECRETS: ${APP_SECRETS}
      CURRENT_GID: ${CURRENT_GID}

      CELERY_ENABLE: 1

      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_EXPIRATION_TIME: ${CELERY_EXPIRATION_TIME}
      CELERY_VERIFICATION_TIME: ${CELERY_VERIFICATION_TIME}
      RABBITMQ_EXPIRATION_TIME: ${RABBITMQ_EXPIRATION_TIME}
      RABBITMQ_VERIFICATION_TIME: ${RABBITMQ_VERIFICATION_TIME}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_SSL_ENABLED: ${RABBITMQ_SSL_ENABLED}

      REDIS_ENABLE: 1
      REDIS_ENABLE_CONNECTOR: ${REDIS_ENABLE_CONNECTOR}
      REDIS_EXPIRATION_TIME: ${REDIS_EXPIRATION_TIME}
      REDIS_VERIFICATION_TIME: ${REDIS_VERIFICATION_TIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      CELERY_BACKEND: ${CELERY_BACKEND}
      MONGO_EXPIRATION_TIME: ${MONGO_EXPIRATION_TIME}
      MONGO_VERIFICATION_TIME: ${MONGO_VERIFICATION_TIME}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      APP_MODE: ${APP_MODE}
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}
      IRODS_EXPIRATION_TIME: ${IRODS_EXPIRATION_TIME}
      IRODS_VERIFICATION_TIME: ${IRODS_VERIFICATION_TIME}

      SMTP_ENABLE_CONNECTOR: ${SMTP_ENABLE_CONNECTOR}
      SMTP_ENABLE: ${ACTIVATE_SMTP}
      SMTP_EXPIRATION_TIME: ${SMTP_EXPIRATION_TIME}
      SMTP_VERIFICATION_TIME: ${SMTP_VERIFICATION_TIME}
      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_NOREPLY: ${SMTP_NOREPLY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
