version: '3'

services:

  proxy:
    environment:
      ACTIVATE: 0

  backend:
    environment:
      ACTIVATE: 0

  postgres:
    environment:
      ACTIVATE: 0

  rabbit:
    restart: always
    environment:
      ACTIVATE: ${ACTIVATE_RABBIT}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}

  mongodb:
    restart: always
    environment:
      ACTIVATE: ${ACTIVATE_MONGODB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  celery:
    restart: on-failure:15
    build: ${PROJECT_DIR}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    command: celery worker --concurrency=1 -Ofair -A restapi.connectors.celery.worker.celery_app -Q celery -n worker-%h
    volumes:
      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}
    environment:
      CELERY_EXTERNAL: 1
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      DEBUG_ENDPOINTS: 1
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PREFIX: ${REDIS_PREFIX}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}

  celeryui:
    restart: on-failure:5
    build: ${PROJECT_DIR}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    hostname: flower
    environment:
      AUTH_ENABLE: 0
      CELERY_EXTERNAL: 1
      CELERYUI_USER: ${CELERYUI_USER}
      CELERYUI_PASSWORD: ${CELERYUI_PASSWORD}
      #############################
      ACTIVATE: ${ACTIVATE_CELERYUI}
      MAIN_LOGIN_ENABLE: 0
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
      DEBUG_ENDPOINTS: 1
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PREFIX: ${REDIS_PREFIX}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}
      # SEADATA ELASTIC LOGS

  ingestion_celery:
    restart: on-failure:15
    build: ${PROJECT_DIR}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    entrypoint: docker-entrypoint-celery
    command: celery worker --concurrency=1 -Ofair -A restapi.connectors.celery.worker.celery_app -Q ingestion -n worker-%h
    # user: developer
    working_dir: /code
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${PROJECT_DIR}/project_configuration.yaml:/code/confs/project_configuration.yaml
      # Vanilla code
      - ${PROJECT_DIR}/backend:/code/${COMPOSE_PROJECT_NAME}
      # From project, if any
      - ${EXTENDED_PROJECT_PATH}/backend:/code/${EXTENDED_PROJECT}
      - ${EXTENDED_PROJECT_PATH}/project_configuration.yaml:/code/confs/extended_project_configuration.yaml
      # JWT tokens secret
      # - jwt_tokens:${JWT_APP_SECRETS}

      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}

      - ${SUBMODULE_DIR}/http-api/restapi:${PYTHON_PATH}/restapi

      - ${VANILLA_DIR}/data/logs:/logs


    networks:
      db_net:
      worker_net:
    # depends_on:
    #   - rabbit
    environment:

      CURRENT_UID: ${CURRENT_UID}
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      EXTENDED_PACKAGE: ${EXTENDED_PROJECT}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
      CURRENT_GID: ${CURRENT_GID}

      CELERY_ENABLE: 1

      CELERY_BROKER: ${CELERY_BROKER}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_SSL_ENABLED: ${RABBITMQ_SSL_ENABLED}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      CELERY_BACKEND: ${CELERY_BACKEND}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      DEBUG_ENDPOINTS: 1
      APP_MODE: ${APP_MODE}
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PREFIX: ${REDIS_PREFIX}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}

      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_NOREPLY: ${SMTP_NOREPLY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  restricted_celery:
    restart: on-failure:5
    build: ${PROJECT_DIR}/builds/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:${RAPYDO_VERSION}
    entrypoint: docker-entrypoint-celery
    command: celery worker --concurrency=1 -Ofair -A restapi.connectors.celery.worker.celery_app -Q restricted -n worker-%h
    # user: developer
    working_dir: /code
    volumes:
      # configuration files
      - ${SUBMODULE_DIR}/rapydo-confs/projects_defaults.yaml:/code/confs/projects_defaults.yaml
      - ${PROJECT_DIR}/project_configuration.yaml:/code/confs/project_configuration.yaml
      # Vanilla code
      - ${PROJECT_DIR}/backend:/code/${COMPOSE_PROJECT_NAME}
      # From project, if any
      - ${EXTENDED_PROJECT_PATH}/backend:/code/${EXTENDED_PROJECT}
      - ${EXTENDED_PROJECT_PATH}/project_configuration.yaml:/code/confs/extended_project_configuration.yaml
      # JWT tokens secret
      # - jwt_tokens:${JWT_APP_SECRETS}

      - ${RESOURCES_LOCALPATH}:${SEADATA_RESOURCES_MOUNTPOINT}

      - ${SUBMODULE_DIR}/http-api/restapi:${PYTHON_PATH}/restapi

      - ${VANILLA_DIR}/data/logs:/logs


    networks:
      db_net:
      worker_net:
    # depends_on:
    #   - rabbit
    environment:

      CURRENT_UID: ${CURRENT_UID}
      VANILLA_PACKAGE: ${COMPOSE_PROJECT_NAME}
      EXTENDED_PACKAGE: ${EXTENDED_PROJECT}
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
      CURRENT_GID: ${CURRENT_GID}

      CELERY_ENABLE: 1

      CELERY_BROKER: ${CELERY_BROKER}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_SSL_ENABLED: ${RABBITMQ_SSL_ENABLED}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      CELERY_BACKEND: ${CELERY_BACKEND}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      #############################
      ACTIVATE: 1
      MAIN_LOGIN_ENABLE: 0
      DEBUG_ENDPOINTS: 1
      APP_MODE: ${APP_MODE}
      DEBUG_LEVEL: ${LOG_LEVEL}
      DOMAIN: ${PROJECT_DOMAIN}
      SEADATA_PROJECT: ${SEADATA_PROJECT}
      SEADATA_EDMO_CODE: ${SEADATA_EDMO_CODE}
      SEADATA_API_IM_URL: ${SEADATA_API_IM_URL}
      SEADATA_API_VERSION: ${SEADATA_API_VERSION}
      # on rancher/celery host filesystem:
      SEADATA_WORKSPACE_INGESTION: ${SEADATA_WORKSPACE_INGESTION}
      SEADATA_WORKSPACE_ORDERS: ${SEADATA_WORKSPACE_ORDERS}
      SEADATA_RESOURCES_MOUNTPOINT: ${SEADATA_RESOURCES_MOUNTPOINT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PREFIX: ${REDIS_PREFIX}
      IRODS_ENABLE: 1
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_HOME: ${IRODS_HOME}
      IRODS_DN: ${IRODS_DN}
      IRODS_PASSWORD: ${IRODS_PASSWORD}
      IRODS_AUTHSCHEME: ${IRODS_AUTHSCHEME}

      SMTP_ADMIN: ${SMTP_ADMIN}
      SMTP_NOREPLY: ${SMTP_NOREPLY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
