name: MyPy

on:
  push:
  workflow_dispatch:

env:
  PROJECT: seadata

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}
          submodule: http-api
      - uses: rapydo/actions/mypy@v1
        with:
          project: ${PROJECT}
          allow_untyped_defs: true
          # install: ...
          ignore: b2stage b2handle flask_oauthlib glom gssapi gdapi irods irods.exception urllib3 tests websocket
