name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        PROJECT: [b2stage, seadata]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: rapydo/actions/install@v1
        with:
          project: ${{ matrix.PROJECT }}
          submodule: http-api
      - uses: rapydo/actions/mypy@v1
        with:
          project: ${{ matrix.PROJECT }}
          allow_untyped_defs: true
          # install: ...
          ignore: b2handle flask_oauthlib gssapi irods plumbum urllib3 tests
